[profile.default]
src = 'contracts'
out = 'artifacts/foundry'
libs = ['lib', 'node_modules']
solc = "0.8.30"
via_ir = true
optimize = true
optimizer_runs = 1000
remappings = [
    'contracts/=contracts/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@gnosis.pm/=node_modules/@gnosis.pm/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'openzeppelin-contracts/=node_modules/@openzeppelin/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-std/=lib/forge-std/src/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
    'bulla-contracts-v2/=node_modules/@bulla/contracts-v2',
    'solmate/=lib/solmate/src'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
